<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'SimplePie\\' => array($vendorDir . '/simplepie/simplepie/src'),
    'Masterminds\\' => array($vendorDir . '/masterminds/html5/src'),
);
