<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'e8b9612bd57a56c6db24fda32a44eac2' => $vendorDir . '/simplepie/simplepie/library/SimplePie.php',
);
