<?php return array(
    'root' => array(
        'name' => 'fivefilters.org/full-text-rss',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '1fd689b4b4aa5a540649492daf5ceb825767be92',
        'type' => 'project',
        'install_path' => __DIR__ . '/../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'fivefilters.org/full-text-rss' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '1fd689b4b4aa5a540649492daf5ceb825767be92',
            'type' => 'project',
            'install_path' => __DIR__ . '/../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fivefilters/readability.php' => array(
            'pretty_version' => 'v3.1.2',
            'version' => '3.1.2.0',
            'reference' => '973fbb0f9c2335153c796dc5dce60f60e3adc347',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fivefilters/readability.php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/uri' => array(
            'pretty_version' => '6.7.2',
            'version' => '6.7.2.0',
            'reference' => 'd3b50812dd51f3fbf176344cc2981db03d10fe06',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/uri',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/uri-interfaces' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => '00e7e2943f76d8cb50c7dfdc2f6dee356e15e383',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/uri-interfaces',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.7.6',
            'version' => '2.7.6.0',
            'reference' => '897eb517a343a2281f11bc5556d6548db7d93947',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'simplepie/simplepie' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => '65b095d87bc00898d8fa7737bdbcda93a3fbcc55',
            'type' => 'library',
            'install_path' => __DIR__ . '/../simplepie/simplepie',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
