<?php return array(
    'root' => array(
        'name' => 'fivefilters.org/full-text-rss',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '10ee0943513276be3b2a4742295071fe158b4c7a',
        'type' => 'project',
        'install_path' => __DIR__ . '/../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'fivefilters.org/full-text-rss' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '10ee0943513276be3b2a4742295071fe158b4c7a',
            'type' => 'project',
            'install_path' => __DIR__ . '/../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => '2c37c6c520b995b761674de3be8455a381679067',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'simplepie/simplepie' => array(
            'pretty_version' => '1.6.0',
            'version' => '1.6.0.0',
            'reference' => '2bdbc51ed1010941c9c5f2cddca433e79665bfe1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../simplepie/simplepie',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
